routes/web.php
<?php

use App\Http\Controllers\MIDletController;
use App\Http\Controllers\MIDletSearchController;
use App\Http\Controllers\StatisticsController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::redirect('/', '/midlets');

Route::resource('midlets', MIDletController::class);
Route::get('midlets/{midlet}/title', [MIDletController::class, 'title'])->name('midlets.title');
Route::get('midlets/{midlet}/icon', [MIDletController::class, 'icon'])->name('midlets.icon');
Route::get('midlets/{midlet}/asset/{asset}', [MIDletController::class, 'asset'])->name('midlets.asset');

Route::get('search', [MIDletSearchController::class, 'index'])->name('search.index');
Route::get('search/results', [MIDletSearchController::class, 'search'])->name('search.search');

Route::get('statistics', [StatisticsController::class, 'index'])->name('statistics.index');

Route::get('about', fn () => view('about.index'))->name('about.index');

app/Models/MIDlet.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class MIDlet extends Model
{
    use HasFactory;

    protected $table = 'midlets';

    protected $fillable = [
        'filename', 'filesize', 'name', 'version', 'screen_width', 'screen_height',
        'count', 'sha256', 'sha1', 'crc32',
    ];

    public function manifestAttributes()
    {
        return $this->hasMany(MIDletManifestAttributes::class, 'midlet_id');
    }

    public function assets()
    {
        return $this->hasMany(MIDletAsset::class, 'midlet_id');
    }

    public function getTitleAttribute()
    {
        return $this->assets
            ->first(fn ($asset) => $asset->type === 'title');
    }

    public function getIconAttribute()
    {
        return $this->assets
            ->first(fn ($asset) => $asset->type === 'icon');
    }

    public function vendor()
    {
        return $this->belongsTo(MIDletVendor::class, 'midlet_vendor_id');
    }

    public function getManifestAttribute(string $key)
    {
        return MIDletManifestAttributes::where('midlet_id', '=', $this->getKey())
            ->where('key', '=', $key)
            ->first()
            ?->value;
    }
}

app/Models/MIDletAsset.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Storage;

class MIDletAsset extends Model
{
    use HasFactory;

    const CLUSTER_SIZE = 10000;

    protected $table = 'midlet_assets';

    protected $fillable = ['ext', 'filename', 'type', 'mime_type'];

    protected static function booted(): void
    {
        static::deleted(function (MIDletAsset $asset) {
            Storage::delete($asset->path);
        });
    }

    public function getPathAttribute()
    {
        return 'assets/' . $this->getClusterFolder() . '/' .
            $this->getKey() . '.' . $this->ext;
    }

    public function getMainTypeAttribute()
    {
        return explode('/', $this->mime_type)[0];
    }

    public function getSubtypeAttribute()
    {
        return explode('/', $this->mime_type)[1];
    }

    private function getClusterFolder()
    {
        return floor($this->getKey() / MIDletAsset::CLUSTER_SIZE);
    }
}

app/Http/Controllers/MIDletController.php
<?php

namespace App\Http\Controllers;

use App\Models\MIDlet;
use App\Models\MIDletAsset;
use App\Models\MIDletVendor;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Storage;

class MIDletController extends Controller
{
    public function index(Request $request)
    {
        $request->validate([
            'vendor' => 'nullable|numeric',
        ]);

        $selectedVendor = null;
        $midlets = MIDlet::orderBy('name');
        if ($request->vendor) {
            $selectedVendor = MIDletVendor::findOrFail($request->vendor);
            $midlets = $midlets->whereHas('vendor', function (Builder $query) use ($selectedVendor) {
                $query->where('id', '=', $selectedVendor->getKey());
            });
        }

        $midlets = $midlets
            ->paginate(20)
            ->withQueryString();

        $vendors = DB::table('midlet_vendors')
            ->selectRaw('midlet_vendors.id, midlet_vendors.name, count(midlets.id) as midlets_count')
            ->join('midlets', 'midlet_vendors.id', 'midlets.midlet_vendor_id')
            ->groupBy('midlet_vendors.id', 'midlet_vendors.name')
            ->orderByRaw('midlets_count desc')
            ->get();

        return view('midlets.index', [
            'midlets'         => $midlets,
            'vendors'         => $vendors,
            'selectedVendor'  => $selectedVendor,
        ]);
    }

    public function show(MIDlet $midlet)
    {
        return view('midlets.show', [
            'midlet' => $midlet,
        ]);
    }

    public function title(MIDlet $midlet)
    {
        return response(Storage::get($midlet->title->path), 200, [
            'Content-Type' => $midlet->title->mime_type,
        ]);
    }

    public function icon(MIDlet $midlet)
    {
        return response(Storage::get($midlet->icon->path), 200, [
            'Content-Type' => $midlet->icon->mime_type,
        ]);
    }

    public function asset(MIDlet $midlet, MIDletAsset $asset)
    {
        return response(Storage::get($asset->path), 200, [
            'Content-Type'        => $asset->mime_type,
            'Content-Disposition' => 'inline; filename="' . $asset->filename . '"',
        ]);
    }
}

resources/views/midlets/asset_audio.blade.php
@switch ($asset->subtype)
    @case('midi')
    @case('amr')
        <a href="javascript:;"
            data-mp-{{ $asset->subtype }}="{{ route('midlets.asset', ['midlet' => $midlet, 'asset' => $asset]) }}">
            <i class="fs-1 bi bi-play-circle"></i>
        </a>
        <a href="{{ route('midlets.asset', ['midlet' => $midlet, 'asset' => $asset]) }}">{{ $asset->filename }}</a>
        <small class="text-muted">{{ $asset->mime_type }}</small>
        @break

    @default
            @include('midlets.asset_default')
    @endswitch

resources/views/midlets/asset_default.blade.php
<i class="text-muted fs-1 bi {{ MIDletHelper::mimeTypeIcon($asset->mime_type) }}"></i><br>
<a href="{{ route('midlets.asset', ['midlet' => $midlet, 'asset' => $asset]) }}">{{ $asset->filename }}</a>
<small class="text-muted">{{ $asset->mime_type }}</small>

resources/views/midlets/asset_image.blade.php
<img src="{{ route('midlets.asset', ['midlet' => $midlet, 'asset' => $asset]) }}" class="mb-1 mw-100">
<a href="{{ route('midlets.asset', ['midlet' => $midlet, 'asset' => $asset]) }}">{{ $asset->filename }}</a>
<small class="text-muted">{{ $asset->mime_type }}</small>

resources/views/midlets/card_midlet.blade.php
<div class="card mb-3 bg-secondary">
    <div class="row g-0 p-2 bg-secondary-dark">
        <div class="col">
            <h3 class="fs-5 card-title text-light m-0">
                <span class="text-muted">[{{ $midlet->getKey() }}]</span>
                <a href="{{ route('midlets.show', $midlet) }}">{{ $midlet->name }}</a>
                @if ($midlet->version !== null)
                    <span class="text-muted">v{{ $midlet->version }}</span>
                @endif
                <span class="float-end text-muted">{{ $midlet->vendor?->name }}</span>
            </h3>
        </div>
    </div>
    <div class="row g-0">
        <div class="col-md-4 p-1">
            @if ($midlet->title !== null)
                <img class="img-fluid w-100 img-rendering-pixelated shadow-sm bg-secondary mb-2"
                    alt="Title image for {{ $midlet->name }}"
                    src="{{ route('midlets.title', $midlet) }}">
            @else
                <div class="text-muted text-center my-3">
                    <i class="bi bi-eye-slash fs-1"></i><br>
                    [no title image]
                </div>
            @endif
        </div>
        <div class="col-md-8">
            <div class="card-body p-0">
                @if ($midlet->icon)
                    <img class="img-rendering-pixelated float-end m-1" style="width: 3rem;"
                        alt="Icon for {{ $midlet->name }}"
                        src="{{ route('midlets.icon', $midlet) }}">
                @endif
                @if ($midlet->count !== 1)
                    <div class="px-2">
                        <i class="bi bi-info-circle text-warning"></i>
                        <span class="text-warning">{{ $midlet->count }} {{ Str::plural('MIDlet', $midlet->count) }}</span>
                    </div>
                @endif
                @if ($midlet->screen_width && $midlet->screen_height)
                    <div class="px-2">
                        <i class="bi bi-display"></i> {{ $midlet->screen_width }}&times;{{ $midlet->screen_height }}
                    </div>
                @endif
                @if ($midlet->assets->isNotEmpty())
                    <div class="px-2">
                        <i class="bi bi-file-earmark"></i> {{ $midlet->assets->count() }} assets
                        <ul class="list-inline p-3">
                            @foreach ($midlet->assets as $asset)
                                <li class="list-inline-item">
                                    <i class="bi {{ MIDletHelper::mimeTypeIcon($asset->mime_type) }}"></i>
                                    <a href="{{ route('midlets.asset', ['midlet' => $midlet, 'asset' => $asset]) }}">{{ $asset->filename }}</a>
                                </li>
                            @endforeach
                        </ul>
                    </div>
                @endif
                @include('midlets.table_manifest')
            </div>
        </div>
    </div>

    <div class="card-footer">
        <div class="row">
            <div class="col">
                {{ $midlet->filename }}
            </div>
            <div class="col text-center">
                crc32: <code>{{ $midlet->crc32 }}</code>
            </div>
            <div class="col text-end">
                {{ FormatHelper::filesize($midlet->filesize) }}
            </div>
        </div>
    </div>
</div>

resources/views/midlets/index.blade.php
@extends('layouts.app')

@section('content')
<div class="row">
    <div class="col-12 col-md-9 order-md-2">
        <h1>{{ FormatHelper::number($midlets->total()) }} MIDlets</h1>

        @isset($selectedVendor)
            <div class="mb-3">
                <a href="{{ route('midlets.index') }}" class="badge bg-info text-decoration-none">
                    &times; Vendor: {{ $selectedVendor->name }}
                </a>
            </div>
        @endif

        <div class="row row-cols-1">
            @foreach ($midlets as $midlet)
                <div class="col">
                    @include('midlets.card_midlet')
                </div>
            @endforeach
        </div>
        {{ $midlets->links() }}
    </div>

    <div class="col-12 col-md-3 order-md-1">
        <h2>Vendors</h2>
        <ul class="list-unstyled">
            @foreach ($vendors as $vendor)
                @if ($loop->index == 10)
                    <li>
                        <ul class="list-unstyled collapse" id="collapse-vendors">
                @endif
                <li>
                    <a href="{{ route('midlets.index', ['vendor' => $vendor->id]) }}">{{ $vendor->name }}</a>
                    <span class="badge bg-secondary-dark">{{ $vendor->midlets_count }}</span>
                </li>
            @endforeach
            @if ($vendors->count() > 9)
                    </ul>
                </li>
                <a href="#" data-bs-toggle="collapse" data-bs-target="#collapse-vendors">more…</a>
            @endif
        </ul>
    </div>

</div>
@endsection

resources/views/midlets/show.blade.php
@extends('layouts.app')

@section('content')
    <div class="row">
        <div class="col">
            @if ($midlet->icon)
                <img class="img-rendering-pixelated float-end m-1" style="width: 3rem;" alt="Icon for {{ $midlet->name }}"
                    src="{{ route('midlets.icon', $midlet) }}">
            @endif
            <h1>
                {{ $midlet->name }}
                @if ($midlet->version !== null)
                    <span class="text-muted">v{{ $midlet->version }}</span>
                @endif
            </h1>
            @if ($midlet->vendor)
                <h2 class="text-muted">
                    <a
                        href="{{ route('search.search', ['vendor' => $midlet->vendor->getKey()]) }}">{{ $midlet->vendor->name }}</a>
                </h2>
            @endif
            <table class="table table-sm table-borderless">
                <tr>
                    <th>File</th>
                    <td>{{ $midlet->filename }} <span
                            class="text-muted">{{ FormatHelper::filesize($midlet->filesize) }}</span></td>
                </tr>
                <tr>
                    <th>crc32</th>
                    <td><code>{{ $midlet->crc32 }}</code></td>
                </tr>
                <tr>
                    <th>sha1</th>
                    <td><code>{{ $midlet->sha1 }}</code></td>
                </tr>
                <tr>
                    <th>sha256</th>
                    <td><code>{{ $midlet->sha256 }}</code></td>
                </tr>
                @if ($midlet->screen_width && $midlet->screen_height)
                <tr>
                    <th>Resolution</th>
                    <td>{{ $midlet->screen_width }}&times;{{ $midlet->screen_height }}</td>
                </tr>
                @endif
            </table>
        </div>
    </div>
    <div class="row mb-3">
        <div class="col-4">
            @if ($midlet->title !== null)
                <img class="img-fluid w-100 img-rendering-pixelated shadow-sm bg-secondary mb-2"
                    alt="Title image for {{ $midlet->name }}" src="{{ route('midlets.title', $midlet) }}">
            @else
                <div class="text-muted text-center my-3">
                    <i class="bi bi-eye-slash fs-1"></i><br>
                    [no title image]
                </div>
            @endif
        </div>
        <div class="col-8">
            @include('midlets.table_manifest')
        </div>
    </div>
    <hr>
    <div class="row row-cols-md-4">
        @foreach ($midlet->assets as $asset)
            <div class="col p-3 d-flex flex-column align-items-center justify-content-between hover-light">
                @if (in_array($asset->main_type, ['image', 'audio']))
                    @include('midlets.asset_' . $asset->main_type)
                @else
                    @include('midlets.asset_default')
                @endif
            </div>
        @endforeach
    </div>
@endsection

@section('scripts')
    <script type="text/javascript" src="//www.midijs.net/lib/midi.js"></script>
    <script type="text/javascript" src="{{ asset("js/amrnb.js") }}"></script>
    <script type="text/javascript" src="{{ asset("js/amrplayer.js") }}"></script>
@endsection

resources/views/midlets/table_manifest.blade.php
<table class="table table-sm table-striped mt-2 overflow-hidden">
    @foreach ($midlet->manifestAttributes->sortBy('key') as $attribute)
        <tr>
            <th class="fw-normal text-muted text-nowrap">{{ $attribute->key }}</th>
            <td class="overflow-hidden">{{ $attribute->value }}</td>
        </tr>
    @endforeach
</table>