routes/web.php
<?php

use App\Http\Controllers\MIDletController;
use App\Http\Controllers\MIDletSearchController;
use App\Http\Controllers\StatisticsController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::redirect('/', '/midlets');

Route::resource('midlets', MIDletController::class);
Route::get('midlets/{midlet}/title', [MIDletController::class, 'title'])->name('midlets.title');
Route::get('midlets/{midlet}/icon', [MIDletController::class, 'icon'])->name('midlets.icon');
Route::get('midlets/{midlet}/asset/{asset}', [MIDletController::class, 'asset'])->name('midlets.asset');

Route::get('search', [MIDletSearchController::class, 'index'])->name('search.index');
Route::get('search/results', [MIDletSearchController::class, 'search'])->name('search.search');

Route::get('statistics', [StatisticsController::class, 'index'])->name('statistics.index');

Route::get('about', fn () => view('about.index'))->name('about.index');

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>@yield('title', 'MIDlet Planet')</title>

    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Oxanium">

    @vite(['resources/sass/app.scss'])
</head>

<body class="bg-secondary">

    <div class="container">
        @include('layouts.nav')

        @yield('content')

        @include('layouts.footer')
    </div>

    @vite(['resources/js/app.js'])

    @yield('scripts')

</body>

</html>

resources/views/layouts/footer.blade.php
<hr>
<p class="text-muted font-special">MIDlet Planet</p>

resources/views/layouts/nav.blade.php
<nav class="navbar navbar-expand-lg mb-3 bg-secondary-dark">
    <div class="container-fluid">
        <a class="navbar-brand" href="{{ route('midlets.index') }}"><i class="bi bi-globe-americas"></i> MIDlet Planet</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item text-nowrap">
                    <a class="nav-link @if (Request::routeIs('midlets.*')) active @endif" aria-current="page" href="{{ route('midlets.index') }}">
                        <i class="bi bi-house"></i> Home
                    </a>
                </li>
                <li class="nav-item text-nowrap">
                    <a class="nav-link @if (Request::routeIs('search.*')) active @endif" aria-current="page" href="{{ route('search.index') }}">
                        <i class="bi bi-search"></i> Search
                    </a>
                </li>
                <li class="nav-item text-nowrap">
                    <a class="nav-link @if (Request::routeIs('statistics.*')) active @endif" aria-current="page" href="{{ route('statistics.index') }}">
                        <i class="bi bi-graph-up"></i> Statistics
                    </a>
                </li>
                <li class="nav-item text-nowrap">
                    <a class="nav-link @if (Request::routeIs('about.*')) active @endif" aria-current="page" href="{{ route('about.index') }}">
                        <i class="bi bi-question-square"></i> About
                    </a>
                </li>
            </ul>
            <div class="container-fluid text-end">
                <span class="navbar-text">
                    The largest collection of MIDlets on the planet!
                </span>
            </div>
        </div>
    </div>
</nav>